language: node_js
node_js:
  - "node"
dist: trusty
addons:
  apt:
    packages:
      - jq

script:
  # Test commands in package.json
  - npm install babel-cli
  - mkdir -p build
  - npm run-script babel
  - npm run-script build
  # Be sure that all provided URLs are valid
  - set -e && for url in $(jq .[].projectWebsite app/data/projects.json | tr -d \"); do if [ "$url" != "null" ]; then echo "${url}"; curl "${url}" -o /dev/null --fail -L; fi; done
  - set -e && for url in $(jq .[].projectRepository app/data/projects.json | tr -d \"); do if [ "$url" != "null" ]; then echo "${url}"; curl "${url}" -o /dev/null --fail -L; fi; done
