name: Deploy GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - dev

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build site and deploy to GHPages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: dev
      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - run: npm ci
      - run: npm install babel-cli
      - run: mkdir -p dist
      - run: npm run babel
      - run: npm run build
      # Be sure that all provided URLs are valid
      - run: set -e && for url in $(jq .[].projectWebsite app/data/projects.json | tr -d \"); do if [ "$url" != "null" ]; then echo "${url}"; curl "${url}" -o /dev/null --fail -L; fi; done
      - run: set -e && for url in $(jq .[].projectRepository app/data/projects.json | tr -d \"); do if [ "$url" != "null" ]; then echo "${url}"; curl "${url}" -o /dev/null --fail -L; fi; done

      # Automatically uploads an artifact from the './_site' directory by default
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
